var PROJECTS = [
  {
    id: 1,
    title: "MediBook",
    sub: "Clinica Medica Online",
    sector: "Salute & Benessere",
    type: "webapp",
    typeLabel: "Web App + Mobile",
    priceMin: 4000,
    priceMax: 9000,
    difficulty: 4,
    description: "Piattaforma di prenotazione visite mediche con area paziente, dashboard medico, notifiche email/SMS e pagamenti online.",
    features: ["Prenotazioni", "Multi-ruolo", "Pagamenti Stripe", "Notifiche SMS"],
    stack: ["Next.js", "Node.js", "PostgreSQL", "Stripe", "React Native"]
  },
  {
    id: 2,
    title: "TableMate",
    sub: "Ristorante & Prenotazioni",
    sector: "Ristorazione",
    type: "vetrina",
    typeLabel: "Sito Vetrina + Booking",
    priceMin: 800,
    priceMax: 2200,
    difficulty: 2,
    description: "Sito vetrina elegante per ristoranti con menu digitale, prenotazione tavoli, gestione eventi e form per richieste catering privato.",
    features: ["Menu digitale", "Prenotazione tavoli", "Form catering", "Gallery foto"],
    stack: ["React", "Tailwind CSS", "Supabase", "Resend"]
  },
  {
    id: 3,
    title: "FitZone",
    sub: "Palestra & Personal Trainer",
    sector: "Sport & Fitness",
    type: "mobile",
    typeLabel: "App Multi-piattaforma",
    priceMin: 3500,
    priceMax: 7500,
    difficulty: 3,
    description: "App iOS/Android/Web per palestre. Prenotazione corsi, tracking allenamenti e acquisto abbonamenti. Il trainer gestisce schede e progressi.",
    features: ["Prenotazione corsi", "Tracking progressi", "Push Notifications", "Abbonamenti"],
    stack: ["Flutter", "Firebase", "Stripe"]
  },
  {
    id: 4,
    title: "CasaViva",
    sub: "Agenzia Immobiliare",
    sector: "Casa & Immobili",
    type: "vetrina",
    typeLabel: "Sito Vetrina Premium",
    priceMin: 2000,
    priceMax: 5000,
    difficulty: 3,
    description: "Sito vetrina di alto livello per agenzie immobiliari con ricerca avanzata, mappa interattiva, schede immobili dettagliate e area riservata agenti.",
    features: ["Ricerca con filtri", "Mappa interattiva", "Form richiesta visita", "Area agenti"],
    stack: ["Next.js", "Prisma", "PostgreSQL", "Mapbox"]
  },
  {
    id: 5,
    title: "LearnHub",
    sub: "Piattaforma E-Learning",
    sector: "Formazione",
    type: "webapp",
    typeLabel: "Web App Complessa",
    priceMin: 5000,
    priceMax: 12000,
    difficulty: 4,
    description: "Piattaforma corsi online con video streaming, quiz interattivi, certificati PDF automatici e community integrata.",
    features: ["Video streaming", "Quiz & Certificati", "Forum community", "Pagamenti"],
    stack: ["Next.js", "Supabase", "Mux Video", "Stripe"]
  },
  {
    id: 6,
    title: "Artigiano Digitale",
    sub: "Portfolio Creativo + CMS",
    sector: "Arte & Creatività",
    type: "vetrina",
    typeLabel: "Sito Vetrina + CMS",
    priceMin: 600,
    priceMax: 1800,
    difficulty: 2,
    description: "Portfolio per fotografi, designer o artisti con CMS headless personalizzato, form preventivo e feed Instagram integrato.",
    features: ["CMS headless", "Form preventivo", "Instagram feed", "Testimonials"],
    stack: ["Astro", "Sanity CMS", "Tailwind", "Vercel"]
  },
  {
    id: 7,
    title: "AutoRent",
    sub: "Noleggio Veicoli",
    sector: "Trasporti & Mobilità",
    type: "webapp",
    typeLabel: "Web App + Mobile",
    priceMin: 4000,
    priceMax: 9000,
    difficulty: 4,
    description: "Sistema di prenotazione noleggio auto/moto con disponibilità in tempo reale, preventivo automatico, check-in digitale e gestione flotta.",
    features: ["Calendario live", "Preventivo automatico", "Check-in digitale", "Gestione flotta"],
    stack: ["Vue.js", "Laravel", "MySQL", "Stripe"]
  },
  {
    id: 8,
    title: "LocalShop",
    sub: "Marketplace Prodotti Locali",
    sector: "E-commerce",
    type: "ecommerce",
    typeLabel: "E-commerce Multi-Venditore",
    priceMin: 7000,
    priceMax: 15000,
    difficulty: 5,
    description: "Marketplace multi-venditore per artigiani e produttori locali con vetrine personalizzabili, analytics e tracking spedizioni.",
    features: ["Multi-venditore", "Analytics venditore", "Tracking spedizioni", "Recensioni"],
    stack: ["Next.js", "Medusa.js", "PostgreSQL", "Stripe"]
  },
  {
    id: 9,
    title: "StayEasy",
    sub: "B&B & Affitti Brevi",
    sector: "Turismo & Hospitality",
    type: "vetrina",
    typeLabel: "Sito Vetrina + Booking",
    priceMin: 2500,
    priceMax: 6000,
    difficulty: 4,
    description: "Sito per B&B con sistema di prenotazione integrato, sync iCal con Airbnb/Booking.com e fatturazione automatica.",
    features: ["Sync iCal Airbnb", "Gestione camere", "Chat host-ospite", "Fatturazione auto"],
    stack: ["React", "Node.js", "MongoDB", "iCal API"]
  },
  {
    id: 10,
    title: "LexDesk",
    sub: "Studio Legale / Consulenza",
    sector: "Servizi Professionali",
    type: "vetrina",
    typeLabel: "Sito Vetrina + CRM Base",
    priceMin: 1500,
    priceMax: 4000,
    difficulty: 3,
    description: "Sito professionale per studi legali o commercialisti con form intake intelligente, prenotazione consulenze e area clienti riservata con documenti.",
    features: ["Form intake cliente", "Prenotazione consulenza", "Area clienti", "Gestione documenti"],
    stack: ["Next.js", "Prisma", "Supabase Auth", "Resend"]
  },
  {
    id: 11,
    title: "FioreDi",
    sub: "Fioreria & Wedding Planner",
    sector: "Arte & Creatività",
    type: "vetrina",
    typeLabel: "Sito Vetrina + Form",
    priceMin: 700,
    priceMax: 1800,
    difficulty: 1,
    description: "Sito vetrina floreale con galleria matrimoni, form richiesta preventivo personalizzato, catalogo prodotti stagionali e integrazione WhatsApp.",
    features: ["Galleria eventi", "Form preventivo", "Catalogo stagionale", "WhatsApp CTA"],
    stack: ["React", "Tailwind CSS", "Formspree"]
  },
  {
    id: 12,
    title: "BarbieraTop",
    sub: "Barberia & Salon",
    sector: "Salute & Benessere",
    type: "vetrina",
    typeLabel: "Sito Vetrina + Booking",
    priceMin: 500,
    priceMax: 1400,
    difficulty: 1,
    description: "Sito vetrina moderno per barberie con sistema prenotazione appuntamenti, presentazione team e listino prezzi interattivo.",
    features: ["Prenota slot", "Team stylist", "Listino prezzi", "Recensioni Google"],
    stack: ["Astro", "Tailwind CSS", "Calendly API"]
  },
  {
    id: 13,
    title: "OfficinaPro",
    sub: "Officina Meccanica",
    sector: "Servizi Professionali",
    type: "vetrina",
    typeLabel: "Sito Vetrina + CRM Tagliandi",
    priceMin: 800,
    priceMax: 2000,
    difficulty: 2,
    description: "Sito per officine con form richiesta preventivo riparazione, prenotazione tagliando online, archivio veicoli del cliente e reminder automatici.",
    features: ["Preventivo online", "Prenota tagliando", "Archivio veicoli", "Reminder email"],
    stack: ["React", "Supabase", "Resend"]
  },
  {
    id: 14,
    title: "NutriLife",
    sub: "Nutrizionista & Dietista",
    sector: "Salute & Benessere",
    type: "vetrina",
    typeLabel: "Sito Vetrina + Area Clienti",
    priceMin: 900,
    priceMax: 2500,
    difficulty: 2,
    description: "Sito vetrina per nutrizionisti con prenotazione consulenza, area clienti per consultare piani alimentari e tracker settimanale peso/obiettivi.",
    features: ["Prenotazione", "Piani alimentari", "Tracker obiettivi", "Area clienti"],
    stack: ["Next.js", "Supabase", "Tailwind CSS"]
  },
  {
    id: 15,
    title: "EventiLux",
    sub: "Agenzia Organizzazione Eventi",
    sector: "Arte & Creatività",
    type: "vetrina",
    typeLabel: "Sito Vetrina Premium",
    priceMin: 1200,
    priceMax: 3500,
    difficulty: 2,
    description: "Sito vetrina di lusso per agenzie eventi con portfolio visivo, modulo richiesta evento personalizzato, counter posti e landing page dedicate.",
    features: ["Portfolio eventi", "Form richiesta", "Landing pages", "Counter posti"],
    stack: ["Next.js", "Sanity CMS", "Tailwind CSS"]
  },
  {
    id: 16,
    title: "ArchStudio",
    sub: "Studio di Architettura",
    sector: "Arte & Creatività",
    type: "vetrina",
    typeLabel: "Sito Vetrina + Portfolio",
    priceMin: 1500,
    priceMax: 4000,
    difficulty: 2,
    description: "Portfolio di alto profilo per studi di architettura con case study interattivi, rendering 3D viewer, form richiesta consulenza e blog editoriale.",
    features: ["Case study", "3D viewer", "Blog CMS", "Form consulenza"],
    stack: ["Astro", "Sanity CMS", "Three.js", "Tailwind"]
  },
  {
    id: 17,
    title: "VetCare",
    sub: "Clinica Veterinaria",
    sector: "Salute & Benessere",
    type: "vetrina",
    typeLabel: "Sito Vetrina + Booking",
    priceMin: 900,
    priceMax: 2500,
    difficulty: 2,
    description: "Sito vetrina per cliniche veterinarie con prenotazione visita per animale domestico, scheda salute pet e promemoria vaccini automatici via email.",
    features: ["Prenotazione visita", "Scheda pet", "Reminder vaccini", "Team medici"],
    stack: ["React", "Supabase", "Resend"]
  },
  {
    id: 18,
    title: "PadelClub",
    sub: "Centro Sportivo & Padel",
    sector: "Sport & Fitness",
    type: "webapp",
    typeLabel: "Web App + Mobile",
    priceMin: 2000,
    priceMax: 5000,
    difficulty: 3,
    description: "Piattaforma prenotazione campi da padel/tennis con gestione tornei, membership, ranking giocatori e notifiche partita.",
    features: ["Prenotazione campi", "Tornei", "Ranking giocatori", "Membership"],
    stack: ["React", "Node.js", "PostgreSQL", "Firebase"]
  },
  {
    id: 19,
    title: "TruccoMaestro",
    sub: "Make-up Artist & Beauty",
    sector: "Arte & Creatività",
    type: "vetrina",
    typeLabel: "Sito Vetrina + Portfolio",
    priceMin: 500,
    priceMax: 1200,
    difficulty: 1,
    description: "Sito vetrina per makeup artist con portfolio before/after, lista servizi con prezzi, form richiesta disponibilità e integrazione Instagram/TikTok.",
    features: ["Before/After", "Listino servizi", "Form disponibilità", "Social feed"],
    stack: ["Astro", "Tailwind CSS", "Instagram API"]
  },
  {
    id: 20,
    title: "CoWorkSpace",
    sub: "Spazi Coworking",
    sector: "Servizi Professionali",
    type: "webapp",
    typeLabel: "Web App + Booking",
    priceMin: 2500,
    priceMax: 6000,
    difficulty: 3,
    description: "Piattaforma prenotazione scrivanie e sale meeting per spazi coworking con abbonamenti, accesso QR e dashboard admin con reportistica occupazione.",
    features: ["Prenota desk/sala", "Abbonamenti", "Accesso QR", "Dashboard admin"],
    stack: ["Next.js", "Prisma", "PostgreSQL", "Stripe"]
  },
  {
    id: 21,
    title: "PsicoStudio",
    sub: "Psicologo & Terapeuta",
    sector: "Salute & Benessere",
    type: "vetrina",
    typeLabel: "Sito Vetrina + Booking",
    priceMin: 900,
    priceMax: 2500,
    difficulty: 2,
    description: "Sito vetrina rassicurante per psicologi con prenotazione primo colloquio, presentazione approcci terapeutici, FAQ e form di contatto anonimo.",
    features: ["Primo colloquio", "Form anonimo", "FAQ interattive", "Approcci terapia"],
    stack: ["Astro", "Tailwind CSS", "Supabase"]
  },
  {
    id: 22,
    title: "MenuQR",
    sub: "Menu Digitale per Locali",
    sector: "Ristorazione",
    type: "webapp",
    typeLabel: "SaaS Micro / Web App",
    priceMin: 1500,
    priceMax: 4000,
    difficulty: 2,
    description: "Piattaforma che permette a bar e ristoranti di gestire il proprio menu digitale via QR code, con aggiornamento in tempo reale, allergeni e modello abbonamento mensile.",
    features: ["QR code", "Gestione menu live", "Allergeni", "Abbonamento SaaS"],
    stack: ["Next.js", "Supabase", "Stripe"]
  },
  {
    id: 23,
    title: "FotoStudio",
    sub: "Fotografo Professionista",
    sector: "Arte & Creatività",
    type: "vetrina",
    typeLabel: "Sito Vetrina + Booking",
    priceMin: 600,
    priceMax: 1600,
    difficulty: 1,
    description: "Portfolio fotografico con gallerie per categoria, form richiesta disponibilità per data evento, pacchetti e prezzi e sistema di consegna foto privato.",
    features: ["Gallerie per categoria", "Richiesta data evento", "Pacchetti prezzi", "Consegna privata"],
    stack: ["Astro", "Sanity CMS", "Cloudinary"]
  },
  {
    id: 24,
    title: "TraslocoFacile",
    sub: "Agenzia Traslochi & Facchinaggio",
    sector: "Servizi Professionali",
    type: "vetrina",
    typeLabel: "Sito Vetrina + Preventivo",
    priceMin: 700,
    priceMax: 1800,
    difficulty: 2,
    description: "Sito per ditte di traslochi con form preventivo intelligente (volume, distanza, piano, ascensore), servizi extra selezionabili e richiesta sopralluogo con mappa.",
    features: ["Form preventivo smart", "Servizi extra", "Richiesta sopralluogo", "Mappa Google"],
    stack: ["React", "Tailwind CSS", "Google Maps API"]
  },
  {
    id: 25,
    title: "AcademiaSport",
    sub: "Scuola Calcio / Sport Giovanile",
    sector: "Sport & Fitness",
    type: "vetrina",
    typeLabel: "Sito Vetrina + Iscrizioni",
    priceMin: 800,
    priceMax: 2200,
    difficulty: 2,
    description: "Sito per società sportive giovanili con iscrizione online ai corsi, area genitori per documenti e comunicazioni, calendario allenamenti e galleria foto/video.",
    features: ["Iscrizione online", "Area genitori", "Calendario", "Galleria partite"],
    stack: ["Next.js", "Supabase", "Resend"]
  },
  {
    id: 26,
    title: "CateringEvent",
    sub: "Catering & Chef a Domicilio",
    sector: "Ristorazione",
    type: "vetrina",
    typeLabel: "Sito Vetrina + Form Richiesta",
    priceMin: 700,
    priceMax: 1800,
    difficulty: 1,
    description: "Sito vetrina per catering privato con menu degustazione, form richiesta per tipo evento (matrimonio, azienda, privato), numero ospiti e galleria eventi passati.",
    features: ["Menu degustazione", "Form tipo evento", "Galleria", "Testimonianze"],
    stack: ["Astro", "Tailwind CSS", "Formspree"]
  },
  {
    id: 27,
    title: "ImmobiliareVR",
    sub: "Agenzia con Virtual Tour",
    sector: "Casa & Immobili",
    type: "webapp",
    typeLabel: "Web App + 3D Tour",
    priceMin: 4000,
    priceMax: 10000,
    difficulty: 4,
    description: "Sito immobiliare avanzato con tour virtuali 360° Matterport, confronto immobili side-by-side, simulatore mutuo e notifiche per nuovi annunci compatibili con i filtri salvati.",
    features: ["Tour 360°", "Simulatore mutuo", "Confronto immobili", "Alert annunci"],
    stack: ["Next.js", "Matterport SDK", "PostgreSQL", "Prisma"]
  },
  {
    id: 28,
    title: "CleanPro",
    sub: "Impresa Pulizie & Sanificazioni",
    sector: "Servizi Professionali",
    type: "vetrina",
    typeLabel: "Sito Vetrina + Preventivo",
    priceMin: 600,
    priceMax: 1500,
    difficulty: 1,
    description: "Sito professionale per imprese di pulizie con form preventivo per tipologia, certificazioni in evidenza, richiesta abbonamento periodico e recensioni verificate.",
    features: ["Preventivo per tipologia", "Certificazioni", "Abbonamento periodico", "Recensioni"],
    stack: ["Astro", "Tailwind CSS", "Supabase"]
  },
  {
    id: 29,
    title: "TattooParlour",
    sub: "Studio Tatuaggi & Piercing",
    sector: "Arte & Creatività",
    type: "vetrina",
    typeLabel: "Sito Vetrina + Booking",
    priceMin: 500,
    priceMax: 1400,
    difficulty: 1,
    description: "Sito vetrina dark/minimal per studi tattoo con portfolio artisti diviso per stile, prenotazione consulenza gratuita e modulo disponibilità per flash day.",
    features: ["Portfolio per stile", "Prenota consulenza", "Flash day", "Team artisti"],
    stack: ["Astro", "Tailwind CSS", "Calendly API"]
  },
  {
    id: 30,
    title: "ProjectHub",
    sub: "Tool Gestione Progetti Freelance",
    sector: "Servizi Professionali",
    type: "webapp",
    typeLabel: "Web App SaaS",
    priceMin: 5000,
    priceMax: 12000,
    difficulty: 4,
    description: "Piattaforma per freelance e piccole agenzie per gestire progetti, clienti, milestone e fatture. Il cliente ha accesso a un portale dedicato per vedere l'avanzamento.",
    features: ["Gestione progetti", "Portale cliente", "Milestone", "Fatturazione"],
    stack: ["Next.js", "Prisma", "PostgreSQL", "Stripe"]
  }
];
